/* Generated By:JavaCC: Do not edit this line. PigScriptParserConstants.java */
package org.apache.pig.tools.pigscript.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PigScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CAT = 6;
  /** RegularExpression Id. */
  int CLEAR = 7;
  /** RegularExpression Id. */
  int FS = 8;
  /** RegularExpression Id. */
  int SH = 9;
  /** RegularExpression Id. */
  int CD = 10;
  /** RegularExpression Id. */
  int COPY = 11;
  /** RegularExpression Id. */
  int COPYFROMLOCAL = 12;
  /** RegularExpression Id. */
  int COPYTOLOCAL = 13;
  /** RegularExpression Id. */
  int DUMP = 14;
  /** RegularExpression Id. */
  int DESCRIBE = 15;
  /** RegularExpression Id. */
  int ALIASES = 16;
  /** RegularExpression Id. */
  int EXPLAIN = 17;
  /** RegularExpression Id. */
  int HELP = 18;
  /** RegularExpression Id. */
  int HISTORY = 19;
  /** RegularExpression Id. */
  int KILL = 20;
  /** RegularExpression Id. */
  int LS = 21;
  /** RegularExpression Id. */
  int MOVE = 22;
  /** RegularExpression Id. */
  int MKDIR = 23;
  /** RegularExpression Id. */
  int PWD = 24;
  /** RegularExpression Id. */
  int QUIT = 25;
  /** RegularExpression Id. */
  int REGISTER = 26;
  /** RegularExpression Id. */
  int USING = 27;
  /** RegularExpression Id. */
  int AS = 28;
  /** RegularExpression Id. */
  int REMOVE = 29;
  /** RegularExpression Id. */
  int REMOVEFORCE = 30;
  /** RegularExpression Id. */
  int SET = 31;
  /** RegularExpression Id. */
  int ILLUSTRATE = 32;
  /** RegularExpression Id. */
  int RUN = 33;
  /** RegularExpression Id. */
  int EXEC = 34;
  /** RegularExpression Id. */
  int PARAM = 35;
  /** RegularExpression Id. */
  int PARAM_FILE = 36;
  /** RegularExpression Id. */
  int SCRIPT = 37;
  /** RegularExpression Id. */
  int DOT = 38;
  /** RegularExpression Id. */
  int OUT = 39;
  /** RegularExpression Id. */
  int BRIEF = 40;
  /** RegularExpression Id. */
  int N = 41;
  /** RegularExpression Id. */
  int SCRIPT_DONE = 42;
  /** RegularExpression Id. */
  int SQL = 47;
  /** RegularExpression Id. */
  int PIG = 110;
  /** RegularExpression Id. */
  int EOL = 111;
  /** RegularExpression Id. */
  int QUOTE = 112;
  /** RegularExpression Id. */
  int SEMICOLON = 113;
  /** RegularExpression Id. */
  int LETTER = 114;
  /** RegularExpression Id. */
  int DIGIT = 115;
  /** RegularExpression Id. */
  int SPECIALCHAR = 116;
  /** RegularExpression Id. */
  int FSSPECIALCHAR = 117;
  /** RegularExpression Id. */
  int FLOAT = 118;
  /** RegularExpression Id. */
  int INTEGER = 119;
  /** RegularExpression Id. */
  int NUMBER = 120;
  /** RegularExpression Id. */
  int IDENTIFIER = 121;
  /** RegularExpression Id. */
  int PATH = 122;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 123;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SQL_START = 1;
  /** Lexical state. */
  int SQL_END = 2;
  /** Lexical state. */
  int PIG_START = 3;
  /** Lexical state. */
  int SINGLE_LINE_COMMENT = 4;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 5;
  /** Lexical state. */
  int IN_STRING = 6;
  /** Lexical state. */
  int IN_COMMAND = 7;
  /** Lexical state. */
  int GENERATE = 8;
  /** Lexical state. */
  int SCHEMA_DEFINITION = 9;
  /** Lexical state. */
  int BAG_CONSTANT = 10;
  /** Lexical state. */
  int IN_BLOCK = 11;
  /** Lexical state. */
  int IN_DOUBLE_QUOTED_STRING = 12;
  /** Lexical state. */
  int PIG_END = 13;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"cat\"",
    "\"clear\"",
    "\"fs\"",
    "\"sh\"",
    "\"cd\"",
    "\"cp\"",
    "\"copyFromLocal\"",
    "\"copyToLocal\"",
    "\"dump\"",
    "\"describe\"",
    "\"aliases\"",
    "\"explain\"",
    "\"help\"",
    "\"history\"",
    "\"kill\"",
    "\"ls\"",
    "\"mv\"",
    "\"mkdir\"",
    "\"pwd\"",
    "\"quit\"",
    "\"register\"",
    "\"using\"",
    "\"as\"",
    "\"rm\"",
    "\"rmf\"",
    "\"set\"",
    "\"illustrate\"",
    "\"run\"",
    "\"exec\"",
    "\"-param\"",
    "\"-param_file\"",
    "\"-script\"",
    "\"-dot\"",
    "\"-out\"",
    "\"-brief\"",
    "\"-n\"",
    "\"scriptDone\"",
    "\"sql\"",
    "\";\"",
    "<token of kind 45>",
    "<token of kind 46>",
    "\"\"",
    "\"split\"",
    "\"define\"",
    "\"store\"",
    "\"import\"",
    "<token of kind 52>",
    "<token of kind 53>",
    "<token of kind 54>",
    "\"\\\'\"",
    "\"`\"",
    "<token of kind 57>",
    "<token of kind 58>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 64>",
    "<token of kind 65>",
    "<token of kind 66>",
    "<token of kind 67>",
    "\"*/\"",
    "<token of kind 69>",
    "<token of kind 70>",
    "\"\\\\\\\'\"",
    "\"\\\'\"",
    "<token of kind 73>",
    "<token of kind 74>",
    "\"\\\\`\"",
    "\"`\"",
    "<token of kind 77>",
    "<token of kind 78>",
    "\"{\"",
    "<token of kind 80>",
    "\";\"",
    "<token of kind 82>",
    "<token of kind 83>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 88>",
    "<token of kind 89>",
    "<token of kind 90>",
    "\"{\"",
    "\"}\"",
    "<token of kind 93>",
    "<token of kind 94>",
    "\"\\\"\"",
    "<token of kind 96>",
    "<token of kind 97>",
    "\"{\"",
    "<token of kind 99>",
    "\"\\\'\"",
    "\"`\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 104>",
    "<token of kind 105>",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "<token of kind 108>",
    "<token of kind 109>",
    "\"\"",
    "<EOL>",
    "\"\\\'\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "<FLOAT>",
    "<INTEGER>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<PATH>",
    "<QUOTEDSTRING>",
  };

}
